### ISSUE TITLE
Annotations of AVEL100k

### ISSUE THREAD

**Issue by JustinYuu** [jasongief/CPSP#1]
Hi Jinxing,

Thanks for your great work!

It seems that the annotations of vggsound_avel100k in label_video_dict.json and video_label_dict.json is video-level rather than segment-level, and I can only find the fine-grained label in vggsound-avel50k_labels.json. Will the segment-level annotations of vggsound_avel100k be available? 

Thanks.

**Comment by jasongief** [comment]
Hi Jiashuo,

Thank you for your attention. I've updated the annotations for the vggsound-avel100k dataset in the original Google Drive. However, the vggsound-avel50k dataset is recommended as it has more accurate annotations. Hope this information could help you.

Best
