### ISSUE TITLE
Question about how to download the dataset

### ISSUE THREAD

**Issue by MengyuanChen21** [jasongief/CPSP#2]
Hello author, first of all, thank you for your excellent work!

I want to run my AVVP model on the proposed VGGSound-AVEL50k dataset. However, I am still confused about what I should do. I want to know how I can download the videos. Besides, is there any convenient script to use?

Thanks a lot!

**Comment by jasongief** [comment]
Hi Mengyuan, thanks for your interest in our work. You may download the YouTube videos by referring to this repository: 
[https://github.com/XuyangSHEN/yt-vid-downloader.git](https://github.com/XuyangSHEN/yt-vid-downloader.git). In short, you can use the provided video ids to download those videos.
